### ISSUE TITLE
Pool does not prefill

### ISSUE THREAD

**Issue by vsevel** [quarkiverse/quarkus-ironjacamar#123]
I have a jms application sending and receiving jms messages using the artemis ra.

I have the following configuration:
```
quarkus:
  ironjacamar:
    ra:
      kind: artemis
      config:
        connection-parameters: host=x;port=x;protocols=CORE;connect-timeout-millis=10000,host=x;port=x;protocols=CORE;connect-timeout-millis=10000
        protocol-manager-factory: org.apache.activemq.artemis.core.protocol.hornetq.client.HornetQClientProtocolManagerFactory
        user: x
        password: x
      cm:
        pool:
          config:
            min-size: 1
            initial-size: 1
            prefill: true
            strict-min: true
    activation-spec:
      myqueue:
        config:
          destination-type: jakarta.jms.Queue
          destination: jms.queue.x
          max-session: '10'
          rebalance-connections: 'true'
```

when I start the application without an active producer, and I get the ironjacamar pool stats, I do not see any connection created.

```
            IronJacamarContainer container = ...
            PoolStatistics stats = container.getConnectionManager().getPool().getStatistics();
            int activeCount = stats.getActiveCount();  ==> 0
```

I would have expected this to be one. 

looking deeper, I can see that without an active producer asking for a context, there is no pool initialization happening.

after I activated a jms producer, I debugged the pool initialization sequence. I ended up stopping in `SemaphoreArrayListManagedConnectionPool`:

```
initialize:177, SemaphoreArrayListManagedConnectionPool (org.jboss.jca.core.connectionmanager.pool.mcp)
init:191, ManagedConnectionPoolFactory (org.jboss.jca.core.connectionmanager.pool.mcp)
create:173, ManagedConnectionPoolFactory (org.jboss.jca.core.connectionmanager.pool.mcp)
getManagedConnectionPool:353, AbstractPool (org.jboss.jca.core.connectionmanager.pool)
getConnection:645, AbstractPool (org.jboss.jca.core.connectionmanager.pool)
getManagedConnection:624, AbstractConnectionManager (org.jboss.jca.core.connectionmanager)
getManagedConnection:440, TxConnectionManagerImpl (org.jboss.jca.core.connectionmanager.tx)
allocateConnection:789, AbstractConnectionManager (org.jboss.jca.core.connectionmanager)
allocateConnection:792, ActiveMQRASessionFactoryImpl (org.apache.activemq.artemis.ra)
createSession:482, ActiveMQRASessionFactoryImpl (org.apache.activemq.artemis.ra)
createSession:673, ActiveMQRASessionFactoryImpl (org.apache.activemq.artemis.ra)
createSession:678, ActiveMQRASessionFactoryImpl (org.apache.activemq.artemis.ra)
validateUser:422, ActiveMQRAConnectionFactoryImpl (org.apache.activemq.artemis.ra)
createContext:379, ActiveMQRAConnectionFactoryImpl (org.apache.activemq.artemis.ra)
createContext:369, ActiveMQRAConnectionFactoryImpl (org.apache.activemq.artemis.ra)
createContext:364, ActiveMQRAConnectionFactoryImpl (org.apache.activemq.artemis.ra)
send:52, MyJMSProducer (com.x.)
```

and specifically this block of code:
```
      // Schedule managed connection pool for prefill
      if ((pc.isPrefill() || pc.isStrictMin()) && p instanceof PrefillPool && pc.getInitialSize() > 0)
      {
         PoolFiller.fillPool(new FillRequest(this, pc.getInitialSize()));
      }
```
the condition is `false` because `p` is a `PoolByCri`, which implements `Pool` but not `PrefillPool`.

if `PoolByCri` can be prefilled, it must be through another mean. or all the `prefill` configuration parameters have no effect.
the second point is that there must be an active producer that triggers getting a connection, else the pool is not initialized. when I set the prefill config params, I would expect the pool to be prefilled, even if I have no active producer.

the hidden requirement behind this issue, is to be able to produce a light health check based on pool stats, as opposed to creating a jms session on a connection.

see also https://github.com/quarkiverse/quarkus-artemis/issues/591#issuecomment-2271071427
